### ISSUE TITLE
Access another page's title / variables

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#13]
I have a website with a "Related" section at the bottom of each article. Right now I generate the links with a `related` variable on each page, like this:

```yaml
---
related:
  - link: article1
    name: A cool article
  - link: article2
    name: Another cool article
```

I'd like to cut down on possible errors (and repetitive work) by providing only the file name, and have Uzu figure out the title of each related article, perhaps by extracting the `title` variable from the appropriate (linked) template. In the future I might want to include other variables in the link text, e.g. the publication date, but for now I'm happy with just the title.

A side benefit of a title-finder is that it would then be easy for Uzu to warn me if I attempt to link to a non-existent page.

**Comment by scmorrison** [comment]
Hi @evanmiller,

I am implementing something similar to this for building a category index, extracting `title`, `date`, and `author` if they are available in the page template.

For `related` links how about something like this:

1. Each item in a `related` yaml dict requires `- link`
2. If an page is found that matches the `link` path (article1, /path/to/article4) then we try extracting `title`, `date`, and `author` from the page if they exist.
3. We return a new hash to the renderer with the extracted variables.

**With this yaml**
```yaml
---
related:
  - link: article1
  - link: article2
  - link: modules.perl6.org
  - link: https://www.perl6.org
    name: The Perl 6 Programming Language
```

**we expose this to the renderer**

```perl
{related => [
    {author => Camelia,
     date   => April 05, 2063,
     link   => article1,
     name   => A cool article},
    {date   => April 05, 2063,
     link   => article2,
     name   => Another cool article},
    {link   => modules.perl6.org},
    {link   => https://www.perl6.org,
     name   => The Perl 6 Programming Language}
]}
```

This would allow me to extract those variables once and use them for both `categories` and `related`.

**Comment by evanmiller** [comment]
@scmorrison That strategy works for me. My only suggestion would be to call it `page` instead of `link`, and apply the algorithm to any array that matches `*_pages` (e.g. `related_pages`). That way I could have multiple (unrelated) page arrays within each template.

**Comment by scmorrison** [comment]
@evanmiller good idea. Let's use these names:

```yaml
related_pages:
    - page: article1
      title: A cool article
    - page: article2
    - page: article3
    - page: https://www.perl6.org
      title: The Perl 6 Programming Language

other_pages:
    - page: article8
      title: Another cool article
    - page: article6
    - page: article4
```

So the following variables will be exposed if available: `page`, `title`, `date`, `author` for each `*_pages` dict.
