### ISSUE TITLE
Build multiple themes / layouts

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#35]
Hi, I have a project with two themes. I'd like a way to build both themes at once instead of manually copying the build directory and changing the config file. I think if multiple themes are present (defined in config?) `uzu build` should output a subdirectory in `build/` for each theme. E.g. `build/website/`, `build/helpbook/`, etc. Then a build-time option could limit builds to a particular theme (maybe same as #18).

**Comment by scmorrison** [comment]
This is a good idea. It will make dealing with multiple themes a lot easier. A few ideas.

We need two options for the cli that will handle targeting builds for specific themes / build directories:

* `--theme` - specify a target theme to build that will override the existing config `theme:` variable.
* `--build-dir` - specify a custom build dir

Then for the build-all-themes-at the same time functionality a method for defining multiple themes in config:

```yaml
- themes:
    - website
      build_dir: ... # optional, use theme name when build_dir not specified
    - helpbook
      build_dir: ...
```

For `uzu watch`, to avoid requiring the user to add a `/helpbook` target path at the beginning of any paths in the templates, I think the best thing to do here is just start a web server for each theme. This would allow for both themes to server at the same time. Increment the port numbers for each theme starting with the base port: theme `default` ~ port 3000, `helpbook` ~ port 3001. And also support explicit ports in the new `themes` yaml:

```yaml
- themes:
    - website         # first theme listed considered default
      build_dir: ...
      port: 4444 # use default port 3000 if not specified
    - helpbook
      build_dir: ...
      port: 4536  # increment starting from default theme port if not specified
```

With those two new cli options and the `themes` config yaml I think this would cover most of the use cases for multiple themes. Running `uzu build` would default to building for all themes defined into their target build directories. Please list anything you think I am missing.

Thanks,  
Sam

**Comment by evanmiller** [comment]
This works for me. I would want the possibility of `build_dir` being an absolute path (since I'm just going to copy it anyway), and also a way to exclude certain pages from particular themes. For my project, all of the article pages will be compiled for both themes, but I have completely separate index templates. (An alternative would be having a `pages` directory inside `themes/xxx/`, but I'd be just as happy with an `exclude-pages` config option. No preference either way.)

**Comment by scmorrison** [comment]
Hi @evanmiller,

I have committed support for multiple theme management. Also added support for `exclude_pages` list in the `config.yml` root and for individual themes. Here is what a multi-theme yaml declaration looks like:

```yaml
themes:
  - default              # Specify a theme directory using the default options
  - summer2017:          
      build_dir: web2017 # Override build director
      port: 4333         # Port to start watch on for this theme.
      exclude_pages:     # List of page template names to ignore for this theme
        - index
```

You can just specify the folder names without the additional theme params, or set overrides for `port`, `build_dir`, and `excluded_pages`.

Also added a new cli option `--theme=summer2017` to restrict `build` and `watch` to a single theme. 

`uzu --theme=default build`
